[package]
name = "examples"
version = "0.1.0"
edition = "2024"

[dependencies]
fairjax_core = { path = "../fairjax_core" }
fairjax = { path = "../fairjax" }
actix = "0.13.5"
tokio = "1.48.0"
rand = "0.9.2"
