[package]
name = "fairjax"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
fairjax_core = { path = "../fairjax_core" }
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = "2.0.106"
