[package]
name = "fairjax_core"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-husky = "1.5.0"
itertools = "0.14.0"

[dev-dependencies.cargo-husky]
version = "1.5.0"
default-features = false
features = ["precommit-hook", "run-cargo-test", "run-cargo-fmt", "run-for-all"]
